# Generated by Django 5.1.7 on 2025-04-03 07:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_attendee_event_reminder_userprofile_delete_usermodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirm_password',
            field=models.CharField(default=django.utils.timezone.now, max_length=154),
            preserve_default=False,
        ),
    ]
