# Generated by Django 5.1.7 on 2025-04-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_userprofile_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=154, null=True),
        ),
    ]
